

cdmon2:
  image: "cdmon2"
  environment:
    - CDMON2_API_PORT=8080
    - CDMON2_TOTAL_NUMBER_OF_CORES=100
    - CDMON2_TOTAL_SIZE_OF_MEMORY=100
    - CDMON2_TOTAL_SIZE_OF_DISK=100
    - CDMON2_MINIMAL_NUMBER_OF_CORES=-1
    - CDMON2_MINIMAL_SIZE_OF_MEMORY=1
    - CDMON2_MININAML_SIZE_OF_DISK=1
  ports:
    - 8080:8080